# This file contains values from Cookiecutter

default_context:
  project_name: "aisym4med"
  repo_name: "time_series_metrics"
  description: "Repository for the development of time series data/model auditing methods."
  organization: "Fraunhofer AICOS"
  license: "No license"
  organization_email: "no-reply@fraunhofer.pt"
  line_length: "120"
  python_minimal_version: "3.8"
