site_name: pyMDMA
site_description: Multimodal Data Metrics for Auditing real and synthetic data
site_author: Marília Barandas

# repo_url: INSERT_REPO_URL_HERE
# edit_uri_template: "browse/docs/{path}"

theme:
    name: material
    user_color_mode_toggle: true
    locale: en
    font: false


plugins:
    - search
    - literate-nav:
        nav_file: SUMMARY.md
    - section-index
    - include-markdown:
        encoding: utf-8
        preserve_includer_indent: false
        dedent: false
        trailing_newlines: true
        comments: true
        rewrite_relative_urls: true
        heading_offset: 0
        recursive: true
    - mkdocstrings:
        default_handler: python
        handlers: # https://mkdocstrings.github.io/python/usage/configuration/docstrings/#list
            python:
                options: #https://github.com/mkdocstrings/python/blob/main/src/mkdocstrings_handlers/python/handler.py
                    docstring_style: numpy
                    ignore_init_summary: true
                    show_if_no_docstring: false
                    show_docstring_functions: false
                    show_docstring_classes: false
                    show_root_heading: true
                    heading_level: 4
                    show_source: true
                    members: false
                    show_bases: false
                    show_symbol_type_heading: true
                    # parameter_headings: true
                    # show_root_heading: true
                    # show_category_heading: True

nav:
    - Getting Started:
        - Home: index.md
        - Installation: installation.md
        # - Tutorials: tutorials.md
        - Contributting: contributing.md
        - Developing: developer.md
    - Image Metrics:
        - Input Validation: image/input_val.md
        - Synthetic Validation: image/synth_val.md
        - Annotation Validation: image/annotation.md
    - Time Series Metrics:
        - Input Validation: time_series/input_val.md
        - Synthetic Validation: time_series/synth_val.md
    - Tabular Metrics:
        - Input Validation: tabular/input_val.md
        - Synthetic Validation: tabular/synth_val.md

# WIP
markdown_extensions:
 - pymdownx.details
 - pymdownx.superfences
 - pymdownx.magiclink
